### ISSUE TITLE
how add a new library?

### ISSUE THREAD

**Issue by denisdemaisbr** [takanuva/arduino-makefile#2]
Hi!

how add a new library properly ?
is need setup/configure arduino ide path (binary dependency) ?

**Comment by takanuva** [comment]
Hello, @denisdemaisbr.

I'm not sure if you should be using this as is - it is really old already. This has nothing to do with the Arduino IDE - you do **not** use the IDE.

Once you update the ./lib/default directory with more up-to-date Arduino code, you can create a new library simply by creating a new directory with it under ./lib, as explained in the README file.

---

**In portuguese**: Cara, você não devia usar isso do jeito que tá, tá desatualizado. E a ideia desse projeto é justamente não usar a IDE. Se você quiser usar, eu recomendo seriamente atualizar a pasta ./lib/default, que tem a biblioteca do Arduino. Pra criar uma nova biblioteca, ou usar uma, é só criar uma nova pasta em ./lib que o sistema cuida do resto.

**Comment by denisdemaisbr** [comment]
na verdade eu acabei achando um plugin pro eclipse. a IDE do arduino é desesperadora; Em todo caso obrigado pela resposta.
